### PR TITLE
Initial version of functional CPS OCaml hugs.

### PR DESCRIPTION
**Pull request by hypatian**
I gave up on a monadic solution, because I don't think a huggable monad is really a useful thing. But this continuation-passing-style implementation is slightly reminiscent of a state monad!

### CODE REVIEW

**Comment by zkat** [comment]
Hi, @hypatian! Do you mind renaming this directory to be `ocaml-cps` or something along those lines, so it doesn't conflict with the other ocaml version I merged in? :)

**Comment by hypatian** [comment]
Oh! No problem. I didn't see another OCaml version in the pull requests
when I added it. I'll try to do that tomorrow (today) some time.

kat.

On Oct 25, 2015, at 19:00, Kat Marchán notifications@github.com wrote:

Hi, @hypatian https://github.com/hypatian! Do you mind renaming this
directory to be ocaml-cps or something along those lines, so it doesn't
conflict with the other ocaml version I merged in? :)

**Comment by zkat** [comment]
Hey Kat,

It's cool -- there were two O'Caml PRs and I happened to merge the other one first before it clicked. No worries ^_^

-Kat

**Comment by zkat** [comment]
Oops, sorry this took a while to accept!

thanks a bunch for this. This one's super cool! :)

``` ocaml
let try_hug =
  Huggable.maybe_hug
    (print_t "Hugs for %s!")
    (print_t "Empathy for %s.")
    (print_t "You should first ask %s about hugs.")

let res = try_hug @hypatian
```

**Pull request merged**
