### PR TITLE
Added Haskell version.

### PR DESCRIPTION
**Pull request by airportyh**

### CODE REVIEW

**Comment by zkat** [comment]
about time we got a Haskell one! so I've been using CC0-1.0 as the license (found in the project root). would you be alright with removing the BSD one and letting the code default to the current license? it would simplify things a bit.

**Comment by airportyh** [comment]
Done!

**Comment by zkat** [comment]
thanks! I'll merge this in a bit (on phone atm)

**Comment by zkat** [comment]
Alright! Thanks again, @airportyh 

``` haskell
putStrLn $ MaybeHug.maybeHug (@airportyh::Cutie)
```

**Pull request merged**
